### PR TITLE
Create bellmanford.cpp

### PR DESCRIPTION
**Pull request by wtaylor17**
I'm a little iffy on the bound for the second `for` loop. Would like confirmation or a discussion about why it needs to be around `V-1`. IMO I believe this to be because we need to make sure all nodes reachable from the negative cycle get the negative infinity weight assigned. For example, if there is a negative cycle of 3 nodes then there can be `V-3` nodes which benefit from the negative cycle, with the farthest being at most `V-3` edges away from the cycle. What do you think @JarateKing ? Alternative options I've seen like [this one](https://en.wikipedia.org/wiki/Bellman%E2%80%93Ford_algorithm) still require at least `T(bellman) + O(VE)` time as well in the worst case, which I guess suggests this code is possibly good enough in the general case.

### CODE REVIEW

**Comment by KosayJabre** [comment]
In terms of the bounds, I think `V-1` is correct because the maximum number of edges in a path of `V` nodes is `V-1`, so after `V-1` iterations all possible paths are neccessarily checked.

**Comment by wtaylor17** [comment]
@KosayJabre the `V-1` is definitely needed for BF to converge, but the second round which also currently happens `V-1` times is for detecting negative cycles (not a feature of the original BF, which would exit). Because there is at least 3 nodes in a cycle, no path from the cycle to something outside of it can actually have `V-1` edges. Looks like tightening the bound requires a DFS though, which defeats the purpose unless the dfs was happening anyway

**Comment by JarateKing** [comment]
[kth](https://github.com/kth-competitive-programming/kactl/blob/master/content/graph/BellmanFord.h) actually uses `V/2+2`, I'm not sure of the technical details myself though (I assume due to sorting).

**Comment by wtaylor17** [comment]
Can confirm that `V/2+2` works with this implementation as well. However, using a constant bound of `2` on the second loop (for neg cycles) works as well. That strange fact + kth citing this exact problem in how they know their version works is very curious

**Pull request merged**
